### ISSUE TITLE
Unable to run properly in Visual Studio

### ISSUE THREAD

**Issue by ChooChoo62** [AcK77/TTGames-Explorer-Rebirth#9]
I may be doing something wrong here, but trying to build the app results in it complaining of missing files. Not sure what to do here.

![2024-10-31 15_16_10-](https://github.com/user-attachments/assets/37ddc37f-4f66-4f42-a59c-2954c3c18ba4)
![2024-10-31 15_16_48-](https://github.com/user-attachments/assets/6059cb40-7550-45e0-b236-70c8331d1e7c)

**Comment by AcK77** [comment]
Restore the nuget packages and try to the source code somewhere where admin access isn’t needed

**Comment by AcK77** [comment]
Have you succeed to build it ?

**Comment by ChooChoo62** [comment]
No. The main folder is in Downloads (I actually tried "reinstalling" it) and the nuget stuff was fine. 
![2024-11-09 10_26_29-Action center](https://github.com/user-attachments/assets/9b633dd5-761a-43f3-9bad-22316eec789f)
![2024-11-09 10_27_19-](https://github.com/user-attachments/assets/aff74f1c-4e70-48ee-bec0-9376839e9cdf)
![2024-11-09 10_27_26-Action center](https://github.com/user-attachments/assets/62d935a2-a627-4f10-9f67-9c38c9061210)
![2024-11-09 10_27_45-Action center](https://github.com/user-attachments/assets/a704ec7d-5178-4277-b9c3-6063a9a339cc)
I suppose, for reference, 
![2024-11-09 10_34_14-Start](https://github.com/user-attachments/assets/7aa50c82-0c80-46a6-9355-832ae6354960)
![2024-11-09 10_36_55-TTGamesExplorerRebirth - Microsoft Visual Studio](https://github.com/user-attachments/assets/4cb0f60a-3c72-4a72-93f2-9fd6268c0112)

**Comment by AcK77** [comment]
You can find some informations about your issue here : https://stackoverflow.com/questions/51348919/couldnt-process-file-resx-due-to-its-being-in-the-internet-or-restricted-zone-o

It's not an issue of the project, it's something one your side.
